"""Setup wizard for Whendoes CLI."""

import os
from pathlib import Path
from rich.console import Console
from rich.prompt import Prompt
from rich.panel import Panel
from rich.table import Table

console = Console()


def setup_wizard() -> bool:
    """Interactive setup wizard for API keys.

    Returns:
        True if setup successful
    """
    console.print(
        Panel(
            "[bold cyan]Whendoes CLI Setup[/bold cyan]\n"
            "Configure your LLM provider to get started",
            expand=False,
        )
    )

    # Check if .env exists
    env_path = Path(".env")
    if env_path.exists():
        response = Prompt.ask(
            "[yellow].env file already exists. Overwrite?[/yellow]",
            choices=["y", "n"],
            default="n",
        )
        if response == "n":
            return True

    # Select provider
    console.print("\n[bold]Available LLM Providers:[/bold]")
    providers = {
        "1": ("anthropic", "Claude (Anthropic)"),
        "2": ("openai", "GPT-4 (OpenAI)"),
        "3": ("groq", "Mixtral (Groq) - Fast & Free"),
        "4": ("gemini", "Gemini (Google)"),
        "5": ("openrouter", "OpenRouter - Multi-model"),
        "6": ("ollama", "Ollama - Local/Offline"),
    }

    for key, (_, name) in providers.items():
        console.print(f"  {key}. {name}")

    choice = Prompt.ask("Select provider", choices=list(providers.keys()))
    provider_name, provider_display = providers[choice]

    # Get API key
    console.print(f"\n[bold]Setting up {provider_display}[/bold]")

    if provider_name == "ollama":
        base_url = Prompt.ask(
            "Ollama base URL",
            default="http://localhost:11434",
        )
        model = Prompt.ask("Model name", default="llama2")
        api_key = ""
    else:
        api_key = Prompt.ask(
            f"Enter your {provider_display} API key",
            password=True,
        )
        if not api_key:
            console.print("[red]API key is required[/red]")
            return False

        model = Prompt.ask(
            "Model name (press Enter for default)",
            default="",
        )
        base_url = ""

    # Write .env file
    env_content = f"""# Whendoes CLI Configuration
# Generated by setup wizard

# LLM Provider
LLM_PROVIDER={provider_name}
"""

    if api_key:
        env_content += f"LLM_API_KEY={api_key}\n"

    if model:
        env_content += f"LLM_MODEL={model}\n"

    if base_url:
        env_content += f"LLM_BASE_URL={base_url}\n"

    env_content += """
# Agent Settings
AGENT_MAX_ITERATIONS=10
AGENT_REQUIRE_APPROVAL=true
AGENT_VERBOSE=false

# CLI Settings
CLI_DEBUG=false
"""

    try:
        Path(".env").write_text(env_content)
        console.print("[green]✓ Configuration saved to .env[/green]")
        return True
    except Exception as e:
        console.print(f"[red]Error writing .env: {e}[/red]")
        return False


def show_provider_info() -> None:
    """Show information about available providers."""
    console.print(
        Panel(
            "[bold]LLM Provider Information[/bold]\n\n"
            "[bold cyan]Anthropic (Claude)[/bold cyan]\n"
            "  • Most capable model\n"
            "  • Requires API key\n"
            "  • Free tier available\n\n"
            "[bold cyan]OpenAI (GPT-4)[/bold cyan]\n"
            "  • Powerful and reliable\n"
            "  • Requires API key\n"
            "  • Paid service\n\n"
            "[bold cyan]Groq (Mixtral)[/bold cyan]\n"
            "  • Fast inference\n"
            "  • Free tier available\n"
            "  • Recommended for beginners\n\n"
            "[bold cyan]Google Gemini[/bold cyan]\n"
            "  • Multimodal capabilities\n"
            "  • Requires API key\n"
            "  • Free tier available\n\n"
            "[bold cyan]OpenRouter[/bold cyan]\n"
            "  • Access to multiple models\n"
            "  • Requires API key\n"
            "  • Pay-per-use\n\n"
            "[bold cyan]Ollama[/bold cyan]\n"
            "  • Run locally on your machine\n"
            "  • No API key needed\n"
            "  • Requires Ollama installation",
            expand=False,
        )
    )
